HW10 is completed
g4web/otus_go pull request #10
Opened 2022-06-20 06:05 UTC by g4web

2022-06-20 11:48 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако подход не удовлетворяет критериям оценки. Рекомендую использовать сторонние пакеты для парсинга json (fastjson, jsoniter, easyjson и т. д.) и получения email в явном виде

Возвращаю задачу на доработку.

2022-06-20 11:48 UTC, agneum commented on hw10_program_optimization/stats.go
> +	for scanner.Scan() {
Рекомендую обратить внимание на [частые ошибки](https://github.com/g4web/otus_go/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)  при выполнении ДЗ №10

2022-06-21 09:02 UTC, g4web commented on hw10_program_optimization/stats.go
> +	for scanner.Scan() {
++

2022-06-21 15:33 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 10 баллов из 10. Принято

Просьба при создании PR использовать шаблон

2022-06-21 15:33 UTC, agneum commented on hw10_program_optimization/stats.go
> +		result[secondLevelDomain] = num
Можно без промежуточной переменной

2022-06-22 01:34 UTC, merged

2022-06-22 01:37 UTC, g4web commented on hw10_program_optimization/stats.go
> +		result[secondLevelDomain] = num
++